### ISSUE TITLE
Error when using tca() function

### ISSUE THREAD

**Issue by sarah-voisin** [cozygene/TCA#10]
Hi,

I am trying to apply TCA to my DNAm dataset (m = 753937 CpGs x n = 75 samples). I have the % of cell types (two cell types only) for each sample. When I run tca(), I get this error message, which I do not understand:

"Error in quadprog::solve.QP(Dmat, dvec, t(Amat), bvec, meq = meq) : 
  matrix D in quadratic function is not positive definite!"
![TCA error](https://user-images.githubusercontent.com/33650106/78937402-c9d45980-7af3-11ea-9d69-5d7267e59160.jpg)

Could you help me? I don't know where I went wrong.

**Comment by E-R** [comment]
EDIT:
This is an edit to my previous comment about applying TCA with only 2 cell types. My previous claim about not being able to use TCA with k=2 is, in general, wrong. Since TCA normalizes cell fractions according to the norms of each individual sample separately, a case of perfect correlation, as I previously suggested, is typically not going to occur (one case where it may occur is if you have very small variability in the fractions across subjects in your sample).

Since you did get a "non-positive definite" error in your case when using 2 cell types, it is most likely because you either have very low variation in cell-type fractions or one or more of your included covariates (i.e. in 'C1') are redundant as they can be linearly explained by the other covariates and the cell type fractions (put differently, a covariate for which you can fit a linear model with R^2 of 1 or almost 1 using the rest of the variables in C1 and the cell fractions in W as explaining variables).
