### ISSUE TITLE
Beta values for each cell type separately

### ISSUE THREAD

**Issue by antgomo** [cozygene/TCA#6]
I am dealing now with a methylation set following your vignette and i want to know two things:

1. If i want to estimate celltype-specific methylation for all cell types for all the cpgs can i run the code as following?

mdl.tca.sub <- tcasub(tca.mdl, features = rownames(X), log_file = "GSE42861.tcasub.log")

# estimate cell-type-specific methylation for the associated site

Z_hat <- tensor(X = X, mdl.tca.sub, log_file = "GSE42861.tensor.log")

The idea is then to extract for all cell type is corresponding beta values for all cpgs

2. I see that previously in your example, you test for cell type specific methylation, cd4. I understand that in my case, i.e get the beta matrix for all cpgs for each cell type, i must not follow this issue, mustn't i?

If not, could you please guide how to get correctly the cell type specific beta values matrix for all cpg's and cell types separately to conduct then differently methylated test between ?

or maybe i am wrong and what i want, i.e all the cpgs differentially methylated between case and control for each cell type, is the **tcareg** test results?

res <- tcareg(X = X, tca.mdl = tca.mdl, y = y,
              test = "custom", null_model = NULL, alternative_model = c(cd8),
              save_results = TRUE, output = "GSE42861.tcareg.CD4",
              log_file = "GSE42861.tcareg.log",
              features_metadata = "HumanMethylationSites.txt")

**Comment by E-R** [comment]
1. Z_hat in your code is a list such that its k-th element corresponds to a matrix with the estimated beta methylation values of the k-th cell type (the matrix is of size m by n, where m is the number of features and n is the number of samples). You can see the documentation in the package manual for the full details about this function.
2. You don't need to use the function 'tensor' in order to test for cell-type-specific associations - you only need to fit the tca model using the 'tca' function and then use 'tcareg' for the association testing.

**Comment by antgomo** [comment]
Many thanks Elior!

The matrix for each cell type is in order to later make plots ( i.e heatmaps and boxplots) for the tcareg results

**Comment by E-R** [comment]
Right, in the vignette I used 'tensor' for making the plots. Note that one might find other uses for the output of 'tensor', but for association testing one should use 'tcareg'.
